# Generated by Django 3.1.1 on 2020-10-10 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devqti', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('email', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='task',
        ),
    ]
